version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql/
    healthcheck:
      test: "mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e \"SHOW DATABASES;\""
      interval: 10s
      timeout: 60s
      retries: 3
    restart: always
  api:
    build: api/
      # context: ./api/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=root
      - SERVER_PORT=8082
    ports:
      - '8080:8082'
    restart: always
    networks:
     - backend
    depends_on:
     db:
      condition: service_healthy
    volumes:
      - api_data:/api/uploads

  # ------ Container frontend ------
  # frontend:
  #   build:
  #     context: ./frontend/
  #   ports:
  #     - '4200:4200'
  #   volumes:
  #     - ./frontend/:/frontend/
  #   restart: always

networks:
  backend: {}

volumes:
  db_data: {}
  api_data: {}